### ISSUE TITLE
tab selection/refresh

### ISSUE THREAD

**Issue by rohal12** [hituro/hituro-makes-macros#1]
for the <<tabs>> macro, how do I set which tab is selected on initialization? Right now it always seems to be the first tab, afaik.
And how do I trigger a refresh of a tab's content?
E.g. when I drink a potion in the potion Tab, I want to refresh the Potion Tab to no longer show it.

**Comment by hituro** [comment]
I assume you mean the `<<tabs>>` macro (Github ate the macro name). If so, you pre-select a tab by passing true (or a variable containing `true`) as the second argument to the tab you want to be the default.

e.g.

```html
<<tabs>>
    <<tab "Potions">>
        POTIONS!
    <</tab>>
    <<tab "Items" true>>
        ITEMS!
    <</tab>>
    <<tab "Keys">>
        KEYS!
    <</tab>>
<</tabs>>
```

Will make "ITEMS" the default.

To reload a tab, use the `<<replace>>` macro targetting the tab you want to refresh, which will have an id of `tabs-content-NAME` where `NAME` is the name of the tab (see https://github.com/hituro/hituro-makes-macros/tree/main/tabs-macro-v2#tab).

For example to replace the "Items" tab above, you want to do `<<replace "#tabs-content-items">>... stuff to replace with ...<</replace>>`.

This is obviously easier if you are using `<<include>>` to include some other passage, like:

```html
<<tabs>>
    <<tab "Potions">>
        POTIONS!
    <</tab>>
    <<tab "Items" true>>
        <<include "items-tab">>
    <</tab>>
<</tabs>>
```

Then in your "items-tab" passage you can have the `<<replace>>` code.

**Comment by rohal12** [comment]
thanks a lot for this explanation, very helpful!
yes I meant the tabs macro, I didn't notice that github ate it.
