### ISSUE TITLE
nested tabs

### ISSUE THREAD

**Issue by rohal12** [hituro/hituro-makes-macros#2]
I tried having nested tabs, meaning one of my `<<tab>>` contains another `<<tabs>>` section with a subcategory.
it works fine with one exception: The child `<<tabs>>` doesn't have a default tab selected when it gets displayed first. They're all set to hidden. I think it might be because the parent <<tabs>> renders its content and then sets all tabs to hidden except of the parent tab that is selcted? Is there an easy way around this?

**Comment by hituro** [comment]
Well spotted!

I've updated the selectors involved in hiding tabs, and pushed an update that should fix your issue
